spring:
  #类似于springmvc中<mvc:resources mapping="/static/**" location="classpath:/static/">
  web:
    resources:
      #设置当前项目的静态资源存放目录
      #注意：配置自定义静态资源目录时，需要添加原有配置项，否则会覆盖
      #classpath表示在类路径下查找静态资源；file表示在操作系统的文件系统下查找资源
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/my/,file:${custom.upload}
  mvc:
    #设置当前项目的静态资源映射路径
#    static-path-pattern: /**
    static-path-pattern: /static/**
    #全局日期格式化, 局部@DateTimeFormat，局部优先级高于全局
    format:
      date: yyyy-MM-dd HH:mm:ss
  #全局json日期格式化，局部@JsonFormat
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #thymeleaf配置
  thymeleaf:
    #classpath:/templates类似于WEB-INF目录也是一个安全目录
#    prefix: classpath:/templates/
#    suffix: .html
    #关闭缓存，开发阶段设置为false
    cache: false

#自定义的配置项
custom:
  upload: d:/pic/

server:
  servlet:
    context-path: /web
